### ISSUE TITLE
Saving Array item in localstorage.

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/Resume-Maker#11]
# Description
For now thier is localstorage set for variable but we have arrays of objects as well which can be stored as JSON.stringify and retrieve as JSON.parse from localstorage.
Code Example: https://github.com/vedant-jain03/Resume-Maker/blob/e038ff072ef4eced58deedca43b1fd97f32b8f73/src/component/Homepage.jsx#L164

**Comment by vedant-jain03** [comment]
@LeaFranz Go Ahead!

**Comment by LeaFranz** [comment]
@vedant-jain03 Added arrays list and skills to local storage. Should the objects for experience, education and projects be added as well?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 Added arrays list and skills to local storage. Should the objects for experience, education and projects be added as well?

Yes
