### ISSUE TITLE
Make issue template and PR template for this repository.

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/Resume-Maker#12]

**Comment by nishant-giri** [comment]
@vedant-jain03, could you kindly assign me this task?

**Comment by vedant-jain03** [comment]
@nishant-giri Go Ahead!

**Comment by nishant-giri** [comment]
Thank you, @vedant-jain03 for assigning me. I will add the templates soon.

**Comment by nishant-giri** [comment]
@vedant-jain03, I've made the required changes. You may have a look.
