### ISSUE TITLE
education can be 0-n

### ISSUE THREAD

**Issue by DONofDESTROY** [vedant-jain03/Resume-Maker#17]
I will add a button that will basically create new education field for the user
the current process is limited upto 2 educaiton, a user may add 10th,12th,UG,PG and so on
I can do this for hacktoberfest

**Comment by vedant-jain03** [comment]
@DONofDESTROY If you can do this , it will be great keep in mind we are passing props to Education.jsx as well so kindly change their also.
Go Ahead
