### ISSUE TITLE
remove un-used or unwanted imports

### ISSUE THREAD

**Issue by Delhi-Babu** [vedant-jain03/Resume-Maker#23]
**Describe the bug**
not an bug but remove unwanted or unused variables so the console will be clean

**Expected behavior**
the console should not have any warnings

**Screenshots**
![Screenshot from 2021-10-07 15-00-00](https://user-images.githubusercontent.com/47606472/136358544-2b79732d-bec2-4293-a81a-1ac52966a2c1.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser brave
 - Version 94.1.30.86

I can do this for hacktoberfest

**Comment by vedant-jain03** [comment]
Go Ahead @DONofDESTROY
