### ISSUE TITLE
Add option for font style

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/Resume-Maker#25]
**Is your feature request related to a problem? Please describe.**
Their is only one default font-family for the resume , adding different fontstyles options gives user different taste.

**Comment by amanbedi1** [comment]
@vedant-jain03  i can work on this issue give me the font styles which suites project.

**Comment by vedant-jain03** [comment]
https://vedant-jain03.github.io/smart-pdf/ Refer this project of mine, it have tool in toolbar that is font-style , you can refer them

**Comment by vedant-jain03** [comment]
> @vedant-jain03 don't you think the font styles used are not good for resume

I just said you to refer the tool not the same font, you can choose font of your own choice but only 5.

**Comment by amanbedi1** [comment]
@vedant-jain03  oh great thanks for clarifications

**Comment by amanbedi1** [comment]
@vedant-jain03  just added the PR for this issue. <a href="https://github.com/vedant-jain03/Resume-Maker/pull/38">#38</a>

**Comment by amanbedi1** [comment]
@vedant-jain03  Just complete this issue. check out <a href="https://github.com/vedant-jain03/Resume-Maker/pull/39">#39</a>.

Feel free to rectify me.
