### ISSUE TITLE
Compilation Error while running locally

### ISSUE THREAD

**Issue by DevRish** [vedant-jain03/Resume-Maker#27]
**Describe the bug**
While running locally using "npm run start" , error encountered : "TypeError: Cannot convert undefined or null to object"

**To Reproduce**
1. Fork this repo and clone it to local device.
2. Run "npm install".
3. Run "npm run start"

**Expected behavior**
The development server should show the website locally.

**Screenshots**
![InChrome](https://user-images.githubusercontent.com/78094670/136432354-72c0389b-d500-4f81-927f-90c2d6014671.png)
![InEdge](https://user-images.githubusercontent.com/78094670/136432401-15ef32f3-71fb-4247-929d-1672e213db26.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome, Microsoft Edge

**Additional Context**
I think if "" is used instead of null, the problem can be fixed. I was planning on working on this project, but got this error and am unable to locally run it in. I request some help regarding this.

**Comment by mr-vijaychauhan** [comment]
its working fine...  

![Screenshot (278)](https://user-images.githubusercontent.com/63604585/136544507-43361053-1f86-40d2-bc24-c4fd41d44c71.png)

**Comment by vedant-jain03** [comment]
@mr-vijaychauhan I also have this error I was busy today I will try to solve the bug ASAP. Sorry for the late reply
