### ISSUE TITLE
Add more color themes

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/Resume-Maker#5]
![bandicam 2021-10-06 16-41-31-819](https://user-images.githubusercontent.com/76901313/136192053-36fcd373-e7a7-4ba0-89b1-8d6552d05077.jpg)

refer this line of code: https://github.com/vedant-jain03/Resume-Maker/blob/85a8e7eb3d4e39f0c68e1fff6873ca277d9bee19/src/component/Homepage.jsx#L339

**Comment by ikurotime** [comment]
I'll make a theme or two!

**Comment by vedant-jain03** [comment]
> I'll make a theme or two!

@ikurotime go ahead!

**Comment by ikurotime** [comment]
Does the theme selector work? The theme hooks doesn't seem to set the theme onClick neither in local env or the github pages.

**Comment by ikurotime** [comment]
Oops! the theme where for the resumes, not the app itself, my bad

**Comment by vedant-jain03** [comment]
> Oops! the themes where for the resumes, not the app itself, my bad
 
Yes! You can refer this pr: https://github.com/vedant-jain03/Resume-Maker/pull/6
